# Generated by Django 4.2.6 on 2023-10-23 05:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coverage',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('tax', models.DecimalField(decimal_places=4, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('coverages', models.ManyToManyField(to='quote.coverage')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.state')),
            ],
        ),
        migrations.CreateModel(
            name='CoverageSurcharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fee', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('coverage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.coverage')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.state')),
            ],
        ),
    ]
