# Generated by Django 4.2.6 on 2023-10-23 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=4, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tax', models.DecimalField(decimal_places=4, max_digits=5)),
                ('coverages', models.ManyToManyField(to='quote.coverage')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('coverage_type', models.CharField(choices=[('BS', 'Basic'), ('PR', 'Premium')], max_length=2)),
                ('coverages', models.ManyToManyField(to='quote.coverage')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.state')),
            ],
        ),
        migrations.AddField(
            model_name='coverage',
            name='state_rates',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.state'),
        ),
    ]
