# Generated by Django 4.2.6 on 2023-10-23 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('quote', '0001_initial'), ('quote', '0002_remove_state_coverages'), ('quote', '0003_alter_coverage_price'), ('quote', '0004_rename_price_coverage_monthly_price_and_more'), ('quote', '0005_coverage_surcharge_fee'), ('quote', '0006_coverage_area'), ('quote', '0007_alter_coverage_area'), ('quote', '0008_alter_coverage_surcharge_fee'), ('quote', '0009_remove_state_coverage_surcharge_coveragesurcharge'), ('quote', '0010_rename_coverage_id_coveragesurcharge_coverage_and_more')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('surcharge_fee', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tax', models.DecimalField(decimal_places=4, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('coverage_type', models.CharField(choices=[('BS', 'Basic'), ('PR', 'Premium')], max_length=2)),
                ('coverages', models.ManyToManyField(to='quote.coverage')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.state')),
            ],
        ),
        migrations.AddField(
            model_name='coverage',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quote.state'),
        ),
        migrations.AlterField(
            model_name='coverage',
            name='surcharge_fee',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='CoverageSurcharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('coverage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.coverage')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.state')),
            ],
        ),
    ]
