# Generated by Django 4.2.6 on 2023-10-23 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='coverages',
        ),
    ]
