# Generated by Django 4.2.6 on 2023-10-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_remove_state_coverages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverage',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
