# Generated by Django 4.2.6 on 2023-10-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0003_alter_coverage_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coverage',
            old_name='price',
            new_name='monthly_price',
        ),
        migrations.RemoveField(
            model_name='coverage',
            name='state_rates',
        ),
        migrations.AddField(
            model_name='state',
            name='coverage_surcharge',
            field=models.ManyToManyField(to='quote.coverage'),
        ),
    ]
