# Generated by Django 4.2.6 on 2023-10-23 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0004_rename_price_coverage_monthly_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverage',
            name='surcharge_fee',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
