# Generated by Django 4.2.6 on 2023-10-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0007_alter_coverage_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverage',
            name='surcharge_fee',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
    ]
