# Generated by Django 4.2.6 on 2023-10-23 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0009_remove_state_coverage_surcharge_coveragesurcharge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coveragesurcharge',
            old_name='coverage_id',
            new_name='coverage',
        ),
        migrations.RenameField(
            model_name='coveragesurcharge',
            old_name='state_id',
            new_name='state',
        ),
    ]
